### ISSUE TITLE
Get rid of blur animation

### ISSUE THREAD

**Issue by guiparmezani** [guiparmezani/delegateit#1]
- Investigate if the other content animation should be removed ass well;
- Make phone number clickable;
- Show full conversation on first iphone image;
- Get rid of Vacation word on first header;
- Make everything more objective (investigate if the third section is really necessary).

**Comment by georgeaf99** [comment]
- Remove the steps in the middle of the page.
- Integrate back end
- Set up transactional emails

**Comment by guiparmezani** [comment]
All items were developed.
